-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql
module Api.Object exposing (..)


type Heatmaps
    = Heatmaps


type Patient
    = Patient


type ResultItem
    = ResultItem


type SearchResult
    = SearchResult


type SemanticId
    = SemanticId


type Series
    = Series


type StatItem
    = StatItem


type Study
    = Study


type Volume
    = Volume
