-- Do not manually edit this file, it was auto-generated by Graphqelm
-- https://github.com/dillonkearns/graphqelm


module Api.Object exposing (Heatmaps(..), Patient(..), ResultItem(..), SearchResult(..), SemanticId(..), Series(..), StatItem(..), Study(..), Volume(..))


type Heatmaps
    = Heatmaps


type Patient
    = Patient


type ResultItem
    = ResultItem


type SearchResult
    = SearchResult


type SemanticId
    = SemanticId


type Series
    = Series


type StatItem
    = StatItem


type Study
    = Study


type Volume
    = Volume
