-- Do not manually edit this file, it was auto-generated by Graphqelm
-- https://github.com/dillonkearns/graphqelm


module Api.Object.Heatmaps exposing (coronalB64, sagitalB64, selection)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.Union
import Graphqelm.Field as Field exposing (Field)
import Graphqelm.Internal.Builder.Argument as Argument exposing (Argument)
import Graphqelm.Internal.Builder.Object as Object
import Graphqelm.Internal.Encode as Encode exposing (Value)
import Graphqelm.OptionalArgument exposing (OptionalArgument(Absent))
import Graphqelm.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| Select fields to build up a SelectionSet for this object.
-}
selection : (a -> constructor) -> SelectionSet (a -> constructor) Api.Object.Heatmaps
selection constructor =
    Object.selection constructor


{-| -}
sagitalB64 : Field (Maybe String) Api.Object.Heatmaps
sagitalB64 =
    Object.fieldDecoder "sagitalB64" [] (Decode.string |> Decode.nullable)


{-| -}
coronalB64 : Field (Maybe String) Api.Object.Heatmaps
coronalB64 =
    Object.fieldDecoder "coronalB64" [] (Decode.string |> Decode.nullable)
