-- Do not manually edit this file, it was auto-generated by Graphqelm
-- https://github.com/dillonkearns/graphqelm


module Api.Object.Patient exposing (birthday, id, name, selection, studies)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.Union
import Graphqelm.Field as Field exposing (Field)
import Graphqelm.Internal.Builder.Argument as Argument exposing (Argument)
import Graphqelm.Internal.Builder.Object as Object
import Graphqelm.Internal.Encode as Encode exposing (Value)
import Graphqelm.OptionalArgument exposing (OptionalArgument(Absent))
import Graphqelm.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| Select fields to build up a SelectionSet for this object.
-}
selection : (a -> constructor) -> SelectionSet (a -> constructor) Api.Object.Patient
selection constructor =
    Object.selection constructor


{-| -}
id : Field (Maybe Api.Scalar.Id) Api.Object.Patient
id =
    Object.fieldDecoder "id" [] (Decode.oneOf [ Decode.string, Decode.float |> Decode.map toString, Decode.int |> Decode.map toString, Decode.bool |> Decode.map toString ] |> Decode.map Api.Scalar.Id |> Decode.nullable)


{-| -}
name : Field (Maybe String) Api.Object.Patient
name =
    Object.fieldDecoder "name" [] (Decode.string |> Decode.nullable)


{-| -}
birthday : Field (Maybe Int) Api.Object.Patient
birthday =
    Object.fieldDecoder "birthday" [] (Decode.int |> Decode.nullable)


{-| -}
studies : SelectionSet decodesTo Api.Object.Study -> Field (Maybe (List (Maybe decodesTo))) Api.Object.Patient
studies object =
    Object.selectionField "studies" [] object (identity >> Decode.nullable >> Decode.list >> Decode.nullable)
