-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql
module Api.Object.Patient exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Field as Field exposing (Field)
import Graphql.Internal.Builder.Object as Object
import Graphql.SelectionSet exposing (SelectionSet)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Api.Object
import Api.Interface
import Api.Union
import Api.Scalar
import Api.InputObject
import Json.Decode as Decode
import Graphql.Internal.Encode as Encode exposing (Value)



{-| Select fields to build up a SelectionSet for this object.
-}
selection : (a -> constructor) -> SelectionSet (a -> constructor) Api.Object.Patient
selection constructor =
    Object.selection constructor
{-| 
-}
id : Field (Maybe Api.Scalar.Id) Api.Object.Patient
id =
      Object.fieldDecoder "id" [] (Object.scalarDecoder |> Decode.map Api.Scalar.Id |> Decode.nullable)


{-| 
-}
name : Field (Maybe String) Api.Object.Patient
name =
      Object.fieldDecoder "name" [] (Decode.string |> Decode.nullable)


{-| 
-}
birthday : Field (Maybe Int) Api.Object.Patient
birthday =
      Object.fieldDecoder "birthday" [] (Decode.int |> Decode.nullable)


{-| 
-}
studies : SelectionSet decodesTo Api.Object.Study -> Field (Maybe (List (Maybe decodesTo))) Api.Object.Patient
studies object_ =
      Object.selectionField "studies" [] (object_) (identity >> Decode.nullable >> Decode.list >> Decode.nullable)
