-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql
module Api.Object.ResultItem exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Field as Field exposing (Field)
import Graphql.Internal.Builder.Object as Object
import Graphql.SelectionSet exposing (SelectionSet)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Api.Object
import Api.Interface
import Api.Union
import Api.Scalar
import Api.InputObject
import Json.Decode as Decode
import Graphql.Internal.Encode as Encode exposing (Value)



{-| Select fields to build up a SelectionSet for this object.
-}
selection : (a -> constructor) -> SelectionSet (a -> constructor) Api.Object.ResultItem
selection constructor =
    Object.selection constructor
{-| 
-}
volume : SelectionSet decodesTo Api.Object.Volume -> Field (Maybe decodesTo) Api.Object.ResultItem
volume object_ =
      Object.selectionField "volume" [] (object_) (identity >> Decode.nullable)


{-| 
-}
finding : SelectionSet decodesTo Api.Object.SemanticId -> Field (Maybe (List (Maybe decodesTo))) Api.Object.ResultItem
finding object_ =
      Object.selectionField "finding" [] (object_) (identity >> Decode.nullable >> Decode.list >> Decode.nullable)


{-| 
-}
x : Field (Maybe Int) Api.Object.ResultItem
x =
      Object.fieldDecoder "x" [] (Decode.int |> Decode.nullable)


{-| 
-}
y : Field (Maybe Int) Api.Object.ResultItem
y =
      Object.fieldDecoder "y" [] (Decode.int |> Decode.nullable)


{-| 
-}
width : Field (Maybe Int) Api.Object.ResultItem
width =
      Object.fieldDecoder "width" [] (Decode.int |> Decode.nullable)


{-| 
-}
height : Field (Maybe Int) Api.Object.ResultItem
height =
      Object.fieldDecoder "height" [] (Decode.int |> Decode.nullable)


{-| 
-}
slice : Field (Maybe Int) Api.Object.ResultItem
slice =
      Object.fieldDecoder "slice" [] (Decode.int |> Decode.nullable)
