-- Do not manually edit this file, it was auto-generated by Graphqelm
-- https://github.com/dillonkearns/graphqelm


module Api.Object.SearchResult exposing (heatmaps, resultsItems, selection, stats, volume)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.Union
import Graphqelm.Field as Field exposing (Field)
import Graphqelm.Internal.Builder.Argument as Argument exposing (Argument)
import Graphqelm.Internal.Builder.Object as Object
import Graphqelm.Internal.Encode as Encode exposing (Value)
import Graphqelm.OptionalArgument exposing (OptionalArgument(Absent))
import Graphqelm.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| Select fields to build up a SelectionSet for this object.
-}
selection : (a -> constructor) -> SelectionSet (a -> constructor) Api.Object.SearchResult
selection constructor =
    Object.selection constructor


{-| -}
volume : SelectionSet decodesTo Api.Object.Volume -> Field (Maybe decodesTo) Api.Object.SearchResult
volume object =
    Object.selectionField "volume" [] object (identity >> Decode.nullable)


{-| -}
resultsItems : SelectionSet decodesTo Api.Object.ResultItem -> Field (Maybe (List (Maybe decodesTo))) Api.Object.SearchResult
resultsItems object =
    Object.selectionField "resultsItems" [] object (identity >> Decode.nullable >> Decode.list >> Decode.nullable)


{-| -}
heatmaps : SelectionSet decodesTo Api.Object.Heatmaps -> Field (Maybe decodesTo) Api.Object.SearchResult
heatmaps object =
    Object.selectionField "heatmaps" [] object (identity >> Decode.nullable)


{-| -}
stats : SelectionSet decodesTo Api.Object.StatItem -> Field (Maybe (List (Maybe decodesTo))) Api.Object.SearchResult
stats object =
    Object.selectionField "stats" [] object (identity >> Decode.nullable >> Decode.list >> Decode.nullable)
