-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql
module Api.Object.SearchResult exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Field as Field exposing (Field)
import Graphql.Internal.Builder.Object as Object
import Graphql.SelectionSet exposing (SelectionSet)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Api.Object
import Api.Interface
import Api.Union
import Api.Scalar
import Api.InputObject
import Json.Decode as Decode
import Graphql.Internal.Encode as Encode exposing (Value)



{-| Select fields to build up a SelectionSet for this object.
-}
selection : (a -> constructor) -> SelectionSet (a -> constructor) Api.Object.SearchResult
selection constructor =
    Object.selection constructor
{-| 
-}
volume : SelectionSet decodesTo Api.Object.Volume -> Field (Maybe decodesTo) Api.Object.SearchResult
volume object_ =
      Object.selectionField "volume" [] (object_) (identity >> Decode.nullable)


{-| 
-}
resultsItems : SelectionSet decodesTo Api.Object.ResultItem -> Field (Maybe (List (Maybe decodesTo))) Api.Object.SearchResult
resultsItems object_ =
      Object.selectionField "resultsItems" [] (object_) (identity >> Decode.nullable >> Decode.list >> Decode.nullable)


{-| 
-}
heatmaps : SelectionSet decodesTo Api.Object.Heatmaps -> Field (Maybe decodesTo) Api.Object.SearchResult
heatmaps object_ =
      Object.selectionField "heatmaps" [] (object_) (identity >> Decode.nullable)


{-| 
-}
stats : SelectionSet decodesTo Api.Object.StatItem -> Field (Maybe (List (Maybe decodesTo))) Api.Object.SearchResult
stats object_ =
      Object.selectionField "stats" [] (object_) (identity >> Decode.nullable >> Decode.list >> Decode.nullable)
