-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql
module Api.Object.SemanticId exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Field as Field exposing (Field)
import Graphql.Internal.Builder.Object as Object
import Graphql.SelectionSet exposing (SelectionSet)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Api.Object
import Api.Interface
import Api.Union
import Api.Scalar
import Api.InputObject
import Json.Decode as Decode
import Graphql.Internal.Encode as Encode exposing (Value)



{-| Select fields to build up a SelectionSet for this object.
-}
selection : (a -> constructor) -> SelectionSet (a -> constructor) Api.Object.SemanticId
selection constructor =
    Object.selection constructor
{-| 
-}
id : Field (Maybe Api.Scalar.Id) Api.Object.SemanticId
id =
      Object.fieldDecoder "id" [] (Object.scalarDecoder |> Decode.map Api.Scalar.Id |> Decode.nullable)


{-| 
-}
textDe : Field (Maybe String) Api.Object.SemanticId
textDe =
      Object.fieldDecoder "textDe" [] (Decode.string |> Decode.nullable)


{-| 
-}
textEn : Field (Maybe String) Api.Object.SemanticId
textEn =
      Object.fieldDecoder "textEn" [] (Decode.string |> Decode.nullable)


{-| 
-}
color : Field (Maybe String) Api.Object.SemanticId
color =
      Object.fieldDecoder "color" [] (Decode.string |> Decode.nullable)
