-- Do not manually edit this file, it was auto-generated by Graphqelm
-- https://github.com/dillonkearns/graphqelm


module Api.Object.SemanticId exposing (color, id, selection, textDe, textEn)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.Union
import Graphqelm.Field as Field exposing (Field)
import Graphqelm.Internal.Builder.Argument as Argument exposing (Argument)
import Graphqelm.Internal.Builder.Object as Object
import Graphqelm.Internal.Encode as Encode exposing (Value)
import Graphqelm.OptionalArgument exposing (OptionalArgument(Absent))
import Graphqelm.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| Select fields to build up a SelectionSet for this object.
-}
selection : (a -> constructor) -> SelectionSet (a -> constructor) Api.Object.SemanticId
selection constructor =
    Object.selection constructor


{-| -}
id : Field (Maybe Api.Scalar.Id) Api.Object.SemanticId
id =
    Object.fieldDecoder "id" [] (Decode.oneOf [ Decode.string, Decode.float |> Decode.map toString, Decode.int |> Decode.map toString, Decode.bool |> Decode.map toString ] |> Decode.map Api.Scalar.Id |> Decode.nullable)


{-| -}
textDe : Field (Maybe String) Api.Object.SemanticId
textDe =
    Object.fieldDecoder "textDe" [] (Decode.string |> Decode.nullable)


{-| -}
textEn : Field (Maybe String) Api.Object.SemanticId
textEn =
    Object.fieldDecoder "textEn" [] (Decode.string |> Decode.nullable)


{-| -}
color : Field (Maybe String) Api.Object.SemanticId
color =
    Object.fieldDecoder "color" [] (Decode.string |> Decode.nullable)
