-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql
module Api.Object.Series exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Field as Field exposing (Field)
import Graphql.Internal.Builder.Object as Object
import Graphql.SelectionSet exposing (SelectionSet)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Api.Object
import Api.Interface
import Api.Union
import Api.Scalar
import Api.InputObject
import Json.Decode as Decode
import Graphql.Internal.Encode as Encode exposing (Value)
import Api.Enum.Modality


{-| Select fields to build up a SelectionSet for this object.
-}
selection : (a -> constructor) -> SelectionSet (a -> constructor) Api.Object.Series
selection constructor =
    Object.selection constructor
{-| 
-}
id : Field (Maybe Api.Scalar.Id) Api.Object.Series
id =
      Object.fieldDecoder "id" [] (Object.scalarDecoder |> Decode.map Api.Scalar.Id |> Decode.nullable)


{-| 
-}
study : SelectionSet decodesTo Api.Object.Study -> Field (Maybe decodesTo) Api.Object.Series
study object_ =
      Object.selectionField "study" [] (object_) (identity >> Decode.nullable)


{-| 
-}
volume : SelectionSet decodesTo Api.Object.Volume -> Field (Maybe decodesTo) Api.Object.Series
volume object_ =
      Object.selectionField "volume" [] (object_) (identity >> Decode.nullable)


{-| 
-}
modality : Field (Maybe Api.Enum.Modality.Modality) Api.Object.Series
modality =
      Object.fieldDecoder "modality" [] (Api.Enum.Modality.decoder |> Decode.nullable)


{-| 
-}
pixelSpacing : Field (Maybe Float) Api.Object.Series
pixelSpacing =
      Object.fieldDecoder "pixelSpacing" [] (Decode.float |> Decode.nullable)


{-| 
-}
sliceThickness : Field (Maybe Float) Api.Object.Series
sliceThickness =
      Object.fieldDecoder "sliceThickness" [] (Decode.float |> Decode.nullable)


{-| 
-}
sliceNum : Field (Maybe Int) Api.Object.Series
sliceNum =
      Object.fieldDecoder "sliceNum" [] (Decode.int |> Decode.nullable)
