-- Do not manually edit this file, it was auto-generated by Graphqelm
-- https://github.com/dillonkearns/graphqelm


module Api.Object.Series exposing (id, modality, pixelSpacing, selection, sliceNum, sliceThickness, study, volume)

import Api.Enum.Modality
import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.Union
import Graphqelm.Field as Field exposing (Field)
import Graphqelm.Internal.Builder.Argument as Argument exposing (Argument)
import Graphqelm.Internal.Builder.Object as Object
import Graphqelm.Internal.Encode as Encode exposing (Value)
import Graphqelm.OptionalArgument exposing (OptionalArgument(Absent))
import Graphqelm.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| Select fields to build up a SelectionSet for this object.
-}
selection : (a -> constructor) -> SelectionSet (a -> constructor) Api.Object.Series
selection constructor =
    Object.selection constructor


{-| -}
id : Field (Maybe Api.Scalar.Id) Api.Object.Series
id =
    Object.fieldDecoder "id" [] (Decode.oneOf [ Decode.string, Decode.float |> Decode.map toString, Decode.int |> Decode.map toString, Decode.bool |> Decode.map toString ] |> Decode.map Api.Scalar.Id |> Decode.nullable)


{-| -}
study : SelectionSet decodesTo Api.Object.Study -> Field (Maybe decodesTo) Api.Object.Series
study object =
    Object.selectionField "study" [] object (identity >> Decode.nullable)


{-| -}
volume : SelectionSet decodesTo Api.Object.Volume -> Field (Maybe decodesTo) Api.Object.Series
volume object =
    Object.selectionField "volume" [] object (identity >> Decode.nullable)


{-| -}
modality : Field (Maybe Api.Enum.Modality.Modality) Api.Object.Series
modality =
    Object.fieldDecoder "modality" [] (Api.Enum.Modality.decoder |> Decode.nullable)


{-| -}
pixelSpacing : Field (Maybe Float) Api.Object.Series
pixelSpacing =
    Object.fieldDecoder "pixelSpacing" [] (Decode.float |> Decode.nullable)


{-| -}
sliceThickness : Field (Maybe Float) Api.Object.Series
sliceThickness =
    Object.fieldDecoder "sliceThickness" [] (Decode.float |> Decode.nullable)


{-| -}
sliceNum : Field (Maybe Int) Api.Object.Series
sliceNum =
    Object.fieldDecoder "sliceNum" [] (Decode.int |> Decode.nullable)
