-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql
module Api.Object.StatItem exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Field as Field exposing (Field)
import Graphql.Internal.Builder.Object as Object
import Graphql.SelectionSet exposing (SelectionSet)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Api.Object
import Api.Interface
import Api.Union
import Api.Scalar
import Api.InputObject
import Json.Decode as Decode
import Graphql.Internal.Encode as Encode exposing (Value)



{-| Select fields to build up a SelectionSet for this object.
-}
selection : (a -> constructor) -> SelectionSet (a -> constructor) Api.Object.StatItem
selection constructor =
    Object.selection constructor
{-| 
-}
semanticId : SelectionSet decodesTo Api.Object.SemanticId -> Field (Maybe decodesTo) Api.Object.StatItem
semanticId object_ =
      Object.selectionField "semanticId" [] (object_) (identity >> Decode.nullable)


{-| 
-}
probability : Field (Maybe Float) Api.Object.StatItem
probability =
      Object.fieldDecoder "probability" [] (Decode.float |> Decode.nullable)
