-- Do not manually edit this file, it was auto-generated by Graphqelm
-- https://github.com/dillonkearns/graphqelm


module Api.Object.StatItem exposing (probability, selection, semanticId)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.Union
import Graphqelm.Field as Field exposing (Field)
import Graphqelm.Internal.Builder.Argument as Argument exposing (Argument)
import Graphqelm.Internal.Builder.Object as Object
import Graphqelm.Internal.Encode as Encode exposing (Value)
import Graphqelm.OptionalArgument exposing (OptionalArgument(Absent))
import Graphqelm.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| Select fields to build up a SelectionSet for this object.
-}
selection : (a -> constructor) -> SelectionSet (a -> constructor) Api.Object.StatItem
selection constructor =
    Object.selection constructor


{-| -}
semanticId : SelectionSet decodesTo Api.Object.SemanticId -> Field (Maybe decodesTo) Api.Object.StatItem
semanticId object =
    Object.selectionField "semanticId" [] object (identity >> Decode.nullable)


{-| -}
probability : Field (Maybe Float) Api.Object.StatItem
probability =
    Object.fieldDecoder "probability" [] (Decode.float |> Decode.nullable)
