-- Do not manually edit this file, it was auto-generated by Graphqelm
-- https://github.com/dillonkearns/graphqelm


module Api.Object.Study exposing (acquisitionDate, description, id, patient, patientAge, selection, series)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.Union
import Graphqelm.Field as Field exposing (Field)
import Graphqelm.Internal.Builder.Argument as Argument exposing (Argument)
import Graphqelm.Internal.Builder.Object as Object
import Graphqelm.Internal.Encode as Encode exposing (Value)
import Graphqelm.OptionalArgument exposing (OptionalArgument(Absent))
import Graphqelm.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| Select fields to build up a SelectionSet for this object.
-}
selection : (a -> constructor) -> SelectionSet (a -> constructor) Api.Object.Study
selection constructor =
    Object.selection constructor


{-| -}
id : Field (Maybe Api.Scalar.Id) Api.Object.Study
id =
    Object.fieldDecoder "id" [] (Decode.oneOf [ Decode.string, Decode.float |> Decode.map toString, Decode.int |> Decode.map toString, Decode.bool |> Decode.map toString ] |> Decode.map Api.Scalar.Id |> Decode.nullable)


{-| -}
patient : SelectionSet decodesTo Api.Object.Patient -> Field (Maybe decodesTo) Api.Object.Study
patient object =
    Object.selectionField "patient" [] object (identity >> Decode.nullable)


{-| -}
series : SelectionSet decodesTo Api.Object.Series -> Field (Maybe (List (Maybe decodesTo))) Api.Object.Study
series object =
    Object.selectionField "series" [] object (identity >> Decode.nullable >> Decode.list >> Decode.nullable)


{-| -}
description : Field (Maybe String) Api.Object.Study
description =
    Object.fieldDecoder "description" [] (Decode.string |> Decode.nullable)


{-| -}
acquisitionDate : Field (Maybe Int) Api.Object.Study
acquisitionDate =
    Object.fieldDecoder "acquisitionDate" [] (Decode.int |> Decode.nullable)


{-| -}
patientAge : Field (Maybe Int) Api.Object.Study
patientAge =
    Object.fieldDecoder "patientAge" [] (Decode.int |> Decode.nullable)
