-- Do not manually edit this file, it was auto-generated by Graphqelm
-- https://github.com/dillonkearns/graphqelm


module Api.Object.Volume exposing (coronalMipPath, id, imageHeight, imageWidth, sagitalMipPath, selection, sliceNum, slicePath)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.Union
import Graphqelm.Field as Field exposing (Field)
import Graphqelm.Internal.Builder.Argument as Argument exposing (Argument)
import Graphqelm.Internal.Builder.Object as Object
import Graphqelm.Internal.Encode as Encode exposing (Value)
import Graphqelm.OptionalArgument exposing (OptionalArgument(Absent))
import Graphqelm.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| Select fields to build up a SelectionSet for this object.
-}
selection : (a -> constructor) -> SelectionSet (a -> constructor) Api.Object.Volume
selection constructor =
    Object.selection constructor


{-| -}
id : Field (Maybe Api.Scalar.Id) Api.Object.Volume
id =
    Object.fieldDecoder "id" [] (Decode.oneOf [ Decode.string, Decode.float |> Decode.map toString, Decode.int |> Decode.map toString, Decode.bool |> Decode.map toString ] |> Decode.map Api.Scalar.Id |> Decode.nullable)


{-| -}
imageWidth : Field (Maybe Int) Api.Object.Volume
imageWidth =
    Object.fieldDecoder "imageWidth" [] (Decode.int |> Decode.nullable)


{-| -}
imageHeight : Field (Maybe Int) Api.Object.Volume
imageHeight =
    Object.fieldDecoder "imageHeight" [] (Decode.int |> Decode.nullable)


{-| -}
sliceNum : Field (Maybe Int) Api.Object.Volume
sliceNum =
    Object.fieldDecoder "sliceNum" [] (Decode.int |> Decode.nullable)


{-| -}
slicePath : Field (Maybe String) Api.Object.Volume
slicePath =
    Object.fieldDecoder "slicePath" [] (Decode.string |> Decode.nullable)


{-| -}
sagitalMipPath : Field (Maybe String) Api.Object.Volume
sagitalMipPath =
    Object.fieldDecoder "sagitalMipPath" [] (Decode.string |> Decode.nullable)


{-| -}
coronalMipPath : Field (Maybe String) Api.Object.Volume
coronalMipPath =
    Object.fieldDecoder "coronalMipPath" [] (Decode.string |> Decode.nullable)
