-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql
module Api.Object.Volume exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Field as Field exposing (Field)
import Graphql.Internal.Builder.Object as Object
import Graphql.SelectionSet exposing (SelectionSet)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Api.Object
import Api.Interface
import Api.Union
import Api.Scalar
import Api.InputObject
import Json.Decode as Decode
import Graphql.Internal.Encode as Encode exposing (Value)



{-| Select fields to build up a SelectionSet for this object.
-}
selection : (a -> constructor) -> SelectionSet (a -> constructor) Api.Object.Volume
selection constructor =
    Object.selection constructor
{-| 
-}
id : Field (Maybe Api.Scalar.Id) Api.Object.Volume
id =
      Object.fieldDecoder "id" [] (Object.scalarDecoder |> Decode.map Api.Scalar.Id |> Decode.nullable)


{-| 
-}
imageWidth : Field (Maybe Int) Api.Object.Volume
imageWidth =
      Object.fieldDecoder "imageWidth" [] (Decode.int |> Decode.nullable)


{-| 
-}
imageHeight : Field (Maybe Int) Api.Object.Volume
imageHeight =
      Object.fieldDecoder "imageHeight" [] (Decode.int |> Decode.nullable)


{-| 
-}
sliceNum : Field (Maybe Int) Api.Object.Volume
sliceNum =
      Object.fieldDecoder "sliceNum" [] (Decode.int |> Decode.nullable)


{-| 
-}
slicePath : Field (Maybe String) Api.Object.Volume
slicePath =
      Object.fieldDecoder "slicePath" [] (Decode.string |> Decode.nullable)


{-| 
-}
sagitalMipPath : Field (Maybe String) Api.Object.Volume
sagitalMipPath =
      Object.fieldDecoder "sagitalMipPath" [] (Decode.string |> Decode.nullable)


{-| 
-}
coronalMipPath : Field (Maybe String) Api.Object.Volume
coronalMipPath =
      Object.fieldDecoder "coronalMipPath" [] (Decode.string |> Decode.nullable)
